name: Prod Validation

on:
  pull_request:
    branches:
      - prod

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: tox
        run: |
          python -m pip install --upgrade pip
          pip install tox==3.27.1
          tox

      - name: Zip Package
        run: |
          mkdir build
          cp -rf eve_ai build
          cd build
          zip -r ../eve_ai.zip . -i .
          cd ..
          mkdir -p lambda_layer/python
          pip install -r eve_ai/lambda_code/requirements.txt -t lambda_layer/python
          cd lambda_layer
          zip -r ../lambda_layers.zip . -i .

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-east-1

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        run: |
          cd terraform
          terraform init -backend-config='bucket=terraform-state-file-aws-cloud-prod'
          terraform fmt -diff ./
          terraform validate
          terraform plan -out=tfplan -var-file='prod.tfvars'
          terraform show tfplan

